swagger: "2.0"
info:
  title: "Backbone service | My suite"
  description: "A backbone service to microservices based suites."
  version: "0.0.1"
host: "admin-service-dot-${GCLOUD_PROJECT}.appspot.com"
basePath: /v1/${SERVICE}
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
securityDefinitions:
    firebase:
      authorizationUrl: ""
      flow: "implicit"
      type: "oauth2"
      # Replace YOUR-PROJECT-ID with your project ID
      x-google-issuer: "https://securetoken.google.com/${GCLOUD_PROJECT}"
      x-google-jwks_uri: "https://www.googleapis.com/service_accounts/v1/metadata/x509/securetoken@system.gserviceaccount.com"
      # Optional. Replace YOUR-CLIENT-ID with your client ID
      x-google-audiences: "${GCLOUD_PROJECT}"
security:
- firebase: []
paths:
  /ping:
    get:
      description: "Test if api is alive."
      operationId: "ping"
      consumes:
        - "application/json"
      parameters:
        - description: "Needed data"
          in: body
          name: data
          required: true
          schema:
            type: object
            $ref: '#/definitions/pongData'
      responses:
        200:
          description: "Service is working"
          schema:
            type: object
            properties:
              Status:
                $ref: '#/definitions/status'
              Message:
                type: string
        401:
          $ref: '#/components/responses/Unauthorized' 
        404:
          $ref: '#/components/responses/BadRequest' 

definitions:
  status:
    type: string
    enum:
      - OK
      - KO

  pongData:
    type: object
    properties:
      name:
        type: string


responses:
  NotFound:
    description: The specified resources was not found
    schema:
      $ref: '#/definitions/errorPayload'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/errorPayload'
  BadRequest:
    description: Bad request
    schema:
      $ref: '#/definitions/errorPayload'